repos:
  - repo: https://github.com/nbQA-dev/nbQA
    rev: 0.11.0  # Use the latest version
    hooks:
      - id: nbqa-isort
      - id: nbqa-black
  - repo: https://github.com/psf/black
    rev: 22.3.0  # Use the latest version
    hooks:
      - id: black
  - repo: https://github.com/pre-commit/mirrors-isort
    rev: v5.10.1  # Use the latest version
    hooks:
      - id: isort
