repos:
  - repo: https://github.com/PyCQA/autoflake
    rev: v2.2.1
    hooks:
    -   id: autoflake
        args: [--remove-all-unused-imports, --in-place]
  - repo: https://github.com/nbQA-dev/nbQA
    rev: 0.11.0  # Use the latest version
    hooks:
      - id: nbqa-isort
        args: ["--nbqa-mutate"]
      - id: nbqa-black
        args: ["--nbqa-mutate"]
  - repo: https://github.com/psf/black
    rev: 22.3.0  # Use the latest version
    hooks:
      - id: black
  - repo: https://github.com/pre-commit/mirrors-isort
    rev: v5.10.1  # Use the latest version
    hooks:
      - id: isort
  - repo: https://github.com/PyCQA/flake8
    rev: 7.0.0
    hooks:
    -   id: flake8
        args: ["--ignore=E501,W503"]