version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: docker/service/Dockerfile
    volumes:
      - .:/workdir
    working_dir: /workdir
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    command: /bin/sh -c "while sleep 1000; do :; done"
